// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	structs "news-service/package/structs"
)

// IRepository is an autogenerated mock type for the IRepository type
type IRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *IRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, dest
func (_m *IRepository) GetAll(ctx context.Context, dest interface{}) error {
	ret := _m.Called(ctx, dest)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetArticlesWithVersions provides a mock function with given fields: ctx, p
func (_m *IRepository) GetArticlesWithVersions(ctx context.Context, p structs.RequestSearchArticle) ([]*structs.ResponseArticleWithVersion, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for GetArticlesWithVersions")
	}

	var r0 []*structs.ResponseArticleWithVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, structs.RequestSearchArticle) ([]*structs.ResponseArticleWithVersion, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, structs.RequestSearchArticle) []*structs.ResponseArticleWithVersion); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*structs.ResponseArticleWithVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, structs.RequestSearchArticle) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id, dest
func (_m *IRepository) GetByID(ctx context.Context, id int64, dest interface{}) error {
	ret := _m.Called(ctx, id, dest)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, interface{}) error); ok {
		r0 = rf(ctx, id, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByIDWithVersion provides a mock function with given fields: ctx, id
func (_m *IRepository) GetByIDWithVersion(ctx context.Context, id int64) (*structs.ResponseArticleWithVersion, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDWithVersion")
	}

	var r0 *structs.ResponseArticleWithVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*structs.ResponseArticleWithVersion, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *structs.ResponseArticleWithVersion); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*structs.ResponseArticleWithVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, payload
func (_m *IRepository) Store(ctx context.Context, payload structs.Article) (int64, error) {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, structs.Article) (int64, error)); ok {
		return rf(ctx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, structs.Article) int64); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, structs.Article) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, payload
func (_m *IRepository) Update(ctx context.Context, payload *structs.Article) (int64, error) {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *structs.Article) (int64, error)); ok {
		return rf(ctx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *structs.Article) int64); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *structs.Article) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateVersioning provides a mock function with given fields: ctx, payload
func (_m *IRepository) UpdateVersioning(ctx context.Context, payload *structs.RequestUpdateVersioning) (int64, error) {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVersioning")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *structs.RequestUpdateVersioning) (int64, error)); ok {
		return rf(ctx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *structs.RequestUpdateVersioning) int64); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *structs.RequestUpdateVersioning) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIRepository creates a new instance of IRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRepository {
	mock := &IRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
